### PR TITLE
Reorganize files

### PR DESCRIPTION
**Pull request by rafaelromcar**
This pull requests aims to help working with the project. It does not change anything about the script, the template or the configuration but only about the organization of the files and folders.

The main folder keeps only the readme and the make file as well as the .gitignore.
Three folders have been created:

-   code: which has all the .go files and configuration files for Golang.
-   template: which has both the script and the xml for the template.
-   zabbix_agent: which has the configuration file that should be placed on the machine which is going to execute the checks.

I have tested the makefile and it does work correctly building the binary file as well as installing it when asked. The binary works as well with --help and also it shows the usual output when you execute it without parameters
`
cant get cluster health from Elasticsearch http://127.0.0.1:9200
└─ Get "http://127.0.0.1:9200/_cluster/health": dial tcp 127.0.0.1:9200: connect: connection refused
`

### CODE REVIEW

**Comment by tears-of-noobs** [comment]
@rafaelromcar Thanks for your contribution. Your suggestion about code reorganization made by some standard or this is your personality vision of how code should be organized?

**Comment by rafaelromcar** [comment]
Hello @tears-of-noobs it is only an organisation I found useful to work with. Just to avoid having all files on the same folder, mixing both code and configuration files. 

I do not have any official or standard documentation to show :) it was just me trying to help, but, of cours, if you do not find it useful, you can just throw it away. No problem.

**Comment by rafaelromcar** [comment]
I just found out this https://github.com/golang-standards/project-layout. If we use it, we could reorganize the folders and have:
- **cmd/zabbix-agent-extension-elasticsearch:** with all the .go files (the code)
- **configs:** with two folders **template** and **agent** to have both the template and the agent configuration for the server.

In that case we would be respecting the standard for Golang projects. Would you like that? If so, I could do the changes on this same MR.

**Comment by tears-of-noobs** [comment]
> I just found out this https://github.com/golang-standards/project-layout. If we use it, we could reorganize the folders and have:
> 
> * **cmd/zabbix-agent-extension-elasticsearch:** with all the .go files (the code)
> * **configs:** with two folders **template** and **agent** to have both the template and the agent configuration for the server.
> 
> In that case we would be respecting the standard for Golang projects. Would you like that? If so, I could do the changes on this same MR.

Yep. This looks good, I would be very appreciated to you if you'll make changes in your PR according to this standard :)

**Comment by rafaelromcar** [comment]
> > I just found out this https://github.com/golang-standards/project-layout. If we use it, we could reorganize the folders and have:
> > 
> > * **cmd/zabbix-agent-extension-elasticsearch:** with all the .go files (the code)
> > * **configs:** with two folders **template** and **agent** to have both the template and the agent configuration for the server.
> > 
> > In that case we would be respecting the standard for Golang projects. Would you like that? If so, I could do the changes on this same MR.
> 
> Yep. This looks good, I would be very appreciated to you if you'll make changes in your PR according to this standard :)

Hello @tears-of-noobs I implemented this. The only thing not respecting this structure is the folder vendor, which right now is generated under cmd/zabbix-agent-extension-elasticsearch/vendor instead of being on the root folder. 

I spoke yesterday with someone who has experience working with Golang and told me to do two things to improve this even more:

- Go modules: migrate the management of the dependencies to Go modules and avoid using the old way of managing the dependencies. Fix the version/commit of the dependencies to avoid problems in the future and/or store the needed version on the vendor folder.
- Makefile: improve it removing the clean-all and the generation of the dependencies from the default behavior. 

I think I will work on both improvements, but in another PR if you do not mind. The reason I'm contributing to this is mainly because we are using it to monitor some Elasticsearch and I would have some improvements to the script and configuration files that I would like to share as well, before working on the makefile and dependencies.

If this PR looks good for you, please go ahead and merge it.

Thanks

-

**Pull request merged**
